### ISSUE TITLE
Authentication issue (80)

### ISSUE THREAD

**Issue by zecoxao** [zecoxao/ps5-pup-decrypt#1]
The payload is lacking privileges to decrypt the last segments:

Log atached below

[logs.txt](https://github.com/zecoxao/ps5-pup-decrypt/files/9790488/logs.txt)

**Comment by LemonHaze420** [comment]
any luck with latest commit?

**Comment by zecoxao** [comment]
@LemonHaze420 it only postpones the issue, it doesn't fix it methinks :P

**Comment by zecoxao** [comment]
try now with astrelsky latest commit

**Comment by zecoxao** [comment]
seems fixed, closing
