### ISSUE TITLE
Build like descripted failed

### ISSUE THREAD

**Issue by Creeeeger** [zecoxao/ps5-pup-decrypt#3]
https://github.com/Creeeeger/ps5-pup-decrypt/actions/runs/5901309187/job/16007255243

I created a workflow with gcc make installed and this is the output

Edit 
I added them to the lflags in the makefile 
It gets compiled
But when i run it it ends in a segmentation fault 

,--allow-multiple-definition,-lc,-Lc

https://github.com/Creeeeger/ps5-pup-decrypt/actions/runs/5901518482/job/16007837077

Here is the run 

I also made an aarch64 Android version
But also there it ends in a segmentation fault 

Ill continue to debug but i keep my research up here
Btw i also "fixed" the ps4 dec but there it also ended in a segmentation fault

If possible could u please describe your build environment better 
Best regs

**Comment by zecoxao** [comment]
the segfault is normal.

**Comment by Creeeeger** [comment]
How to deal with it? 
I want to run the program but I get the segfault
So what to do to run it properly?

**Comment by Creeeeger** [comment]
Okay it's as it looks like something with the input path and the state variable


But still I don't get it

**Comment by Creeeeger** [comment]
Okay I had to run it through the elf loader and compile it with 
Gcc 7.5.0 on Ubuntu 18.04
